insert into city (name, province) values('Andalucía', 'Almeria');
insert into city (name, province) values('Andalucía', 'Cadiz');
insert into city (name, province) values('Andalucía', 'Cordoba');
insert into city (name, province) values('Andalucía', 'Granada');
insert into city (name, province) values('Andalucía', 'Jaen');
insert into city (name, province) values('Andalucía', 'Huelva');
insert into city (name, province) values('Andalucía', 'Malaga');
insert into city (name, province) values('Andalucía', 'Sevilla');
insert into city (name, province) values('Aragon', 'Huesca');
insert into city (name, province) values('Aragon', 'Teruel');
insert into city (name, province) values('Aragon', 'Zaragoza');
insert into city (name, province) values('Asturias', 'Oviedo');
insert into city (name, province) values('Baleares', 'Palma de Mallorca');
insert into city (name, province) values('Canarias', 'Santa Cruz de Tenerife');
insert into city (name, province) values('Canarias', 'Las Palmas de Gran Canaria');
insert into city (name, province) values('Cantabria', 'Santander');
insert into city (name, province) values('Castilla-La Mancha', 'Albacete');
insert into city (name, province) values('Castilla-La Mancha', 'Ciudad Real');
insert into city (name, province) values('Castilla-La Mancha', 'Cuenca');
insert into city (name, province) values('Castilla-La Mancha', 'Guadalajara');
insert into city (name, province) values('Castilla-La Mancha', 'Toledo');
insert into city (name, province) values('Castilla y León', 'Ávila');
insert into city (name, province) values('Castilla y León', 'Burgos');
insert into city (name, province) values('Castilla y León', 'León');
insert into city (name, province) values('Castilla y León', 'Salamanca');
insert into city (name, province) values('Castilla y León', 'Segovia');
insert into city (name, province) values('Castilla y León', 'Soria');
insert into city (name, province) values('Castilla y León', 'Valladolid');
insert into city (name, province) values('Castilla y León', 'Zamora');
insert into city (name, province) values('Cataluña', 'Barcelona');
insert into city (name, province) values('Cataluña', 'Tarragona');
insert into city (name, province) values('Cataluña', 'Lérida');
insert into city (name, province) values('Cataluña', 'Girona');
insert into city (name, province) values('Comunidad Valenciana', 'Alicante');
insert into city (name, province) values('Comunidad Valenciana', 'Castellón de la Plana');
insert into city (name, province) values('Comunidad Valenciana', 'Valencia');
insert into city (name, province) values('Extremadura', 'Badajoz');
insert into city (name, province) values('Extremadura', 'Cáceres');
insert into city (name, province) values('Galicia', 'La Coruña');
insert into city (name, province) values('Galicia', 'Lugo');
insert into city (name, province) values('Galicia', 'Orense');
insert into city (name, province) values('Galicia', 'Pontevedra');
insert into city (name, province) values('Madrid', 'Madrid');
insert into city (name, province) values('Murcia', 'Murcia');
insert into city (name, province) values('Navarra', 'Pamplona');
insert into city (name, province) values('Pais Vasco', 'Bilbao');
insert into city (name, province) values('Pais Vasco', 'San Sevastián');
insert into city (name, province) values('Pais Vasco', 'Vitoria');
insert into city (name, province) values('La Rioja', 'Logroño');
insert into city (name, province) values('Ceuta', 'Ceuta');
insert into city (name, province) values('Melilla', 'Melilla');